import { MODULE_NAME } from "./constants";

export const REMOVE_FAVORITE = `${MODULE_NAME}.REMOVE_FAVORITE`;
export const ADD_FAVORITE = `${MODULE_NAME}.ADD_FAVORITE`;
export const GET_MOVIES = `${MODULE_NAME}.GET_MOVIES`;
export const TOGGLE_MODAL = `${MODULE_NAME}.TOGGLE_MODAL`;
export const GET_MOVIES_SUCCESS = `${MODULE_NAME}.GET_MOVIES_SUCCESS`;
export const GET_MOVIES_FAILURE = `${MODULE_NAME}.GET_MOVIES_FAILURE`;
